FIND_PATH(SHARED_ACTORS_INCLUDE_DIR SharedActors
          $ENV{DELTA_SHARED_CODE}/include
          ${CMAKE_SOURCE_DIR}/ext/include
)

#where to find the SharedCode lib dir
SET(DELTA_SHARED_LIB_SEARCH_PATH
    $ENV{DELTA_SHARED_CODE}/build/lib
    $ENV{DELTA_SHARED_CODE}/build/bin
    ${SHARED_ACTORS_INCLUDE_DIR}/../build/lib
    ${CMAKE_SOURCE_DIR}/ext/lib
)

#list of libs that must be found in order to "find" the Shared code
SET(DELTA_SHARED_LIBRARIES SharedActors)

MACRO(FIND_SHARED_LIBRARY LIB_VAR LIB_NAME)
      FIND_LIBRARY(${LIB_VAR} NAMES ${LIB_NAME}
      PATHS
      ${DELTA_SHARED_LIB_SEARCH_PATH}
)
ENDMACRO(FIND_SHARED_LIBRARY LIB_VAR LIB_NAME)

#FIND_SHARED_LIBRARY(EXPERIMENT_FRAMEWORK_LIBRARY       ExperimentFramework)
#FIND_SHARED_LIBRARY(EXPERIMENT_FRAMEWORK_LIBRARY_DEBUG ExperimentFrameworkd)
#FIND_SHARED_LIBRARY(GUI_MANAGER_LIBRARY                GUIManager)
#FIND_SHARED_LIBRARY(GUI_MANAGER_LIBRARY_DEBUG          GUIManagerd)
#FIND_SHARED_LIBRARY(SHADOW_MANAGER_LIBRARY             ShadowManager)
#FIND_SHARED_LIBRARY(SHADOW_MANAGER_LIBRARY_DEBUG       ShadowManagerd)
FIND_SHARED_LIBRARY(SHARED_ACTORS_LIBRARY              SharedActors)
FIND_SHARED_LIBRARY(SHARED_ACTORS_LIBRARY_DEBUG        SharedActorsd)
#FIND_SHARED_LIBRARY(SHARED_COMMON_AI_LIBRARY           CommonAI)
#FIND_SHARED_LIBRARY(SHARED_COMMON_AI_LIBRARY_DEBUG     CommonAId)
#FIND_SHARED_LIBRARY(SHARED_HUD_LIBRARY                 SharedHUD)
#FIND_SHARED_LIBRARY(SHARED_HUD_LIBRARY_DEBUG           SharedHUDd)
#FIND_SHARED_LIBRARY(SHARED_MINIMAP_LIBRARY             Minimap)
#FIND_SHARED_LIBRARY(SHARED_MINIMAP_LIBRARY_DEBUG       Minimapd)
#FIND_SHARED_LIBRARY(SHARED_RAGDOLL_LIBRARY             dtRagdoll)
#FIND_SHARED_LIBRARY(SHARED_RAGDOLL_LIBRARY_DEBUG       dtRagdolld)
#FIND_SHARED_LIBRARY(SHARED_SERIALIZATION_LIBRARY       SerializationFPA)
#FIND_SHARED_LIBRARY(SHARED_SERIALIZATION_LIBRARY_DEBUG SerializationFPAd)
#FIND_SHARED_LIBRARY(SHARED_UTIL_LIBRARY                SharedUtil)
#FIND_SHARED_LIBRARY(SHARED_UTIL_LIBRARY_DEBUG          SharedUtild)
#FIND_SHARED_LIBRARY(VOIP_LIBRARY                       VOIP)
#FIND_SHARED_LIBRARY(VOIP_LIBRARY_DEBUG                 VOIPd)
#FIND_SHARED_LIBRARY(WATER_LIBRARY                      Water)
#FIND_SHARED_LIBRARY(WATER_LIBRARY_DEBUG                Waterd)

#convienent list of libraries to link with when using dtCore
SET(SHARED_ACTORS_LIBRARIES
    optimized ${SHARED_ACTORS_LIBRARY}      debug ${SHARED_ACTORS_LIBRARY_DEBUG}
    )

#handle the QUIETLY and REQUIRED arguments and set SHAREDACTORS_FOUND to TRUE if
#all listed vairables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(SharedActors DEFAULT_MSG SHARED_ACTORS_INCLUDE_DIR
                                                           SHARED_ACTORS_LIBRARY)
